CREATE SEQUENCE user_seq START WITH 1000;
CREATE SEQUENCE news_seq START WITH 10000;
CREATE SEQUENCE motorsport_seq START WITH 100;
CREATE SEQUENCE chatroom_seq START WITH 10;
CREATE SEQUENCE chatroom_msq_seq START WITH 200;
CREATE SEQUENCE race_seq START WITH 11000;
CREATE SEQUENCE comment_seq START WITH 2000;
